---
title: "Söderberg 1986 Individual Based Model"
author: "Carl Vigren"
date: "10/28/2021"
output: html_document
references: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(forester)
```

```{r}
#Soderbergh_IBM

#Set site params.
latitude <- 56.8
longitude <- 14.9
epsg <- 4326

#Inventory
SIH100 <- 20
SI_species <- "Picea abies"


#Derived site information below.

#sf point for automatic elevation return with Amazon Web Service through elevatr.
point <- sf::st_sfc(sf::st_point(x=c(longitude,latitude)))
sf::st_crs(point) <- epsg
altitude <- elevatr::get_elev_point(point,prj=paste0('EPSG:',epsg),src="aws",zoom=14)$elevation

county <- forester::county_sweden(latitude=latitude,longitude = longitude,epsg=epsg)
distance_to_coast <- forester::coast_distance(latitude = latitude,longitude = longitude,epsg = epsg)
#continental <-
#maritime <-









#From Start
#Tree species, diameter and age at start. Included or thinned after every period.

#Management




#Estimate Basal area increment next 5 yrs
#add to starting points



#Volume estimated by form height function at start and end of period.
#Volume increment is the difference.

#Thinning. Thinned trees are removed. Growth functions dummy variables cover reaction.

## Natural mortality: if below xx, Bengtsson 1978, if above, Soderberg 1986.
## All trees continue to grow, if not distribution of deaths known. Punishment of total.-
## Trees which die have 50% productivity during next period.

## Age ring index, Jonsson (1972) , Jonsson & Hägglund (1979) correction of growth.


```
