---
title: "Development of the Top Height Concept in Swedish Forest Science"
author: "Carl Vigren"
date: "8/16/2021"
output: html_document
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

During the middle of the 19th century, central European foresters based in the germanic *kleinstater* were looking for a metric which reliably could be used to distinguish the productivity of forest stands.

Early estimates of volume were made in the form of

$$
V = Basal~area\times\overline{height}\times Air~percentage~of~Mass 
$$

Examples can be given in, e.g. @jonson1914 . Wherein the air percentage of mass was calibrated roughly from plots run by the Royal College of Forestry.

However, both diameter and mean height are heavily influenced by silvicultural operations, e.g. PCT, thinning.

@fries1964, p. 15, provides a compact introduction to the development of the top height concept.

Up until the time of writing his dissertation (1964), *dominant height* or *top height*, was defined by @näslund1936, p. 48, as the height predicted by the height function at a diameter of $\bar{D} + 3\sigma$ , mean diameter + 3 standard deviations.

> Based on the above definition, Professor Manfred Näslund, late Professor Lars Tirén as well as professors Erik Hagberg, Charles Carbonnier and Bertil Matérn recommended a for practical use more suitable definition: the height according to the height curve for the arithmetic mean diameter of the first tenth of the trees, when these have been ordered after falling diameter at breast height, $h_{10\%}$ . @fries1964

> It has yet to be proven that the height trajectory is valid not only for the thickest diameter, but also for the height for a certain relative amount within a stand, for example the 10% thickest trees' heights. Matérn has conducted such a study, which has not been published:

@fries1964 p. 26 recounts an unpublished study by Professor Bertil Matérn which were announced in a memorandum, @carbonnier1959.

> The study concerns the arithmetic mean diameter for the 50 and 100 thickest trees per ha as well as for the 5 and 10% thickest trees both before thinning during the establishment of the permanent plots (time 1) and at the latest revision (time 2). The study shows that the trees, which at time 2 were among the 5% thickest trees, at time 1 had approximately the same mean diameter as the 5% thickest trees at time 1. The same applies for the 10% thickest trees, but not for the 50 or 100 thickest trees per ha.

Since top height is mostly undisturbed by normal silvicultural operations, by the 1970's, site index had emerged as a concept from which one could distinguish the productivity of a stand by their top height and age at breast height (time to breast height is very variable even on sites with similar productivity as a result of extraneous factors such as browsing by rodents, frost or particularly injurious pests such as fungi, e.g. *Phacidium infestans*).

Particularly studies undertaken together with the material collected under @näslund1971 during *The Great Yield Investigation*, [@hägglund1972;@hägglund1973;@hägglund1974] gained prominence and favor as a result of the large underlying material.

As stated by @fries1974 , now an Associate Professor at the dept. of forest production at the Royal College of Forestry, site index is a function of the mean height and age of the 100 thickest trees per hectare.

Due to the inherent difficulty and time-consuming process of identifying these trees, in practice site index would be distinguished by sample plots.

-   0.1 ha (17.84 m radius) arithmetic mean height and age at breast height for the thickest 10 trees.

-   0.02 ha (7.98 m radius) - two thickest trees.

-   0.01 ha (5.64 m radius) - thickest tree.

Method was found to underestimate site index by \~1.5% if site index was estimated from plots of size 0.01 ha.

@matérn1976 shows that for a theoretical stand of size 0.1 ha, an relatively unbiased estimate can be achieved by measuring the two thickest trees on one plot of radius 9.317 m (0.027 ha).

## \newpage

## Sources of Error

As it turned out, many of the height trajectories built on the material collected during *The Great Yield Investigation* [@näslund1971] would later be found erroneous:

> Older stands tend to indicate lower site index than younger on equal site. [@tegnhammar1992]

Tegnhammar realised that for such a complex phenomenon, it was necessary to distinguish between a 'real' and a 'delusive' trend. The following two sections on the 'Real' and 'Delusive' trend is translated freely from his dissertation (1992):

### Real trend

**I:** The rotational period of a stand is dependent on the productivity - the higher producitivity, the lower the rotational age.

[Comment:]{.ul} This is self-explanatory from the point of view of management - and should contribute to the 'real age-trend'. If this process has been in place for at least one rotational period, and during this time having maintained a similar final felling age, it will contribute to a real age-trend above this final age; for stands younger than this final felling age, the stand productivity distribution will be even.

**II:** There is a systematic change in planted species. If for example a Scots Pine stand on good sites after clear-felling is replaced by a Norway Spruce stand, and a corresponding shift to Pine occurs after clear-felling of Spruce stands on poor sites, a 'real' age trend for Spruce emerges.

[Comment:]{.ul} This process would also have come with the respective 'positive age-trend' for Pine. However, this is not the case.

**III:** If old fields of good productivity is reclassified as forest land and subsequently to a great degree afforested with Spruce, a 'real' age trend for Spruce can emerge.

### Delusive trend

**IV:** The height trajectories are erroneous: they are too flat. Real stands have a more crooked development of the dominant height and therefore indicate a lower site index with increasing age. Another similar suggestion is that the old stand would amass a large pool of nutrients which a subsequent stand would be able to translate into a more rapid development in youth and a more crooked height trajectory.

[Comment:]{.ul} Neither empirical or theoretical evidence has been presented that support the notion that the height trajectories 'are too flat'. During function construction by stem-cut sample trees from the *Great Yield Investigation*, a height rearrangement effect was taken into account and corrected for, however not an age-rearrangement effect. This would have resulted in that the curves are instead too crooked, and result in a weak positive age-trend.

**V:** Forests with low ages today, "the new forest", has a better genetic constitution than the old forests and therefore *indicates* a higher SI than the old on equal site.

**VI:** Young forests have in general received a better start as a result of improved practice in regeneration (soil scarification, planting) and management such as PCT [^1] , thinning, than did the old forests. Young forests therefore *indicate* a higher SI than the old on equal site.

[^1]: Pre-Commercial Thinning

[Comment:]{.ul} A consequent transition from the 'high-grading' / 'selection-felling' which in large parts of the country have been common since the 1920's did not occur until the beginning of the 1950's. This change in forest management should thus primarily affect stands with a breast height under 30 years. However one would do well to keep in mind that a clear-felling epoch with replanting or seeding was widely practiced before the 'Wallmo-epoch' began: also during the period 1920-1950. It is obvious that regeneration- and stand management operations affect the stands capacity to indicate productivity. It is possible that the requirements that the stand *must not have been high-graded* or that the *young stands development must not have been hindered* have not been obeyed. Most likely as a result of the large difficulties in assessing prior management.

**VII:** Sometimes site index estimation by height, the 'H- method', is used on dominant trees with 'hidden' stem breaks.

**VIII:** Site productivity has improved with time, primarily due to increased atmospheric nitrogen deposition. This leads to a larger increase of SI estimated by the 'H-method' in younger stands than in older, because the young stands have been affected by the increased productivity for a larger part of their lives than have the older stands (other reasons might include a more conducive temperature climate or increased $CO_2$ concentration).

### Strength of Trend

By comparing the influence on basal area increment of an adjusted SI-H versus reference SIH, using a model of form $$ln(IG_5)=f(SIH_{corr}, age_{dom},competition)$$

where $SIH_{corr}=SIH + k*(age_{dom}-15)$, @tegnhammar1992 could show that residuals were minimised for an age-trend (k) of *0.5-0.8 dm/year* .

## References 
