Norwegian_vegetation_types_regeneration <- function(){
  cat("Selection of forest types from Fremstad (1997).\nRecruitment capacity per Lexerød (2005).\n")
  dplyr::tibble("Code"=seq_len(22),"Vegetation"=c(
    "Cladonio-Pinetum boreale (Caj. 21) K-Lund 67",
    "Calamagrostiso lapponicae-Pinetum K-Lund 67",
    "Barbilophozio-Pinetum Br.-Bl. et Siss. 39 em. K-Lund 67",
    "Eu-Piceetum myrtillitosum K-Lund 81",
    "Eu-Piceetum dryopteridetosum K-Lund 81",
    "Eu-Piceetum athyrietosum K-Lund 81",
    "Melico-Piceetum typicum K-Lund 81",
    "Aconito-Piceetum Bjørnd. 80",
    "Melico-Piceetum Convallario-Pinetum Bjørnd.80",
    "Molinio-Arrhenattheretea Tx. 37",
    "Alno-incanae-Prunetum padi K-Lund 71 ex Aune 7",
    "Populo-Quercetum Tx. 51",
    "Melico-Quercetum Bjørnstad 71",
    "Dentario-Fagetum (Zlarn. 35) Hartm. 53 em. Lohm. 62",
    "Ulmo-Tilietum K-Lund 69",
    "Alno-incanae-Fraxinetum K-Lund 69",
    "Chamaemoro-Piceetum K.-Lund 62",
    "Dryopterido thelypteris-Salicetum cinereae K.-Lund 81",
    "Oxycocco quadripetali-Pinetum K.-Lund 81",
    "Caricion canescenti nigrae Koch 26 em. Klika 34",
    "Vaccinio-Callunetum Büker 42",
    "Cladonio-Betuletum (Nordh. 43) K.-Lund 73"
  ),
  "Norway Spruce recruitment"=c(
    "poor",
    "intermediate",
    "intermediate",
    "good",
    "good",
    "poor",
    "intermediate",
    "poor",
    "good",
    "poor",
    "intermediate",
    "poor",
    "poor",
    "poor",
    "poor",
    "intermediate",
    "good",
    "good",
    "poor",
    "poor",
    "poor",
    "poor"

  ),
  "Scots Pine recruitment"=c(
    "good",
    "good",
    "good",
    "intermediate",
    "poor",
    "poor",
    "poor",
    "poor",
    "good",
    "poor",
    "poor",
    "poor",
    "poor",
    "poor",
    "poor",
    "poor",
    "intermediate",
    "poor",
    "good",
    "poor",
    "poor",
    "poor"
  ),
  "Birch recruitment"=c(
    "poor",
    "poor",
    "intermediate",
    "intermediate",
    "intermediate",
    "intermediate",
    "good",
    "good",
    "good",
    "poor",
    "intermediate",
    "poor",
    "poor",
    "poor",
    "poor",
    "intermediate",
    "good",
    "good",
    "good",
    "poor",
    "poor",
    "good"
  ),
  "Other broadleaves recruitment"=c(
    "poor",
    "poor",
    "poor",
    "poor",
    "poor",
    "poor",
    "intermediate",
    "intermediate",
    "poor",
    "poor",
    "good",
    "poor",
    "good",
    "poor",
    "good",
    "good",
    "poor",
    "poor",
    "poor",
    "poor",
    "poor",
    "poor"
  )

  )
}
